#!/bin/bash

# CONFIGURACION
this_file="buscar" # name of this file
list_file="lista.txt"


# INSTALACION DE ALIAS
alias_file="$HOME/.$this_file"
if [ -r $alias_file ] && [ -s $alias_file ]
then
        # El archivo ~/.$alias_file existe.
	:
else
        echo "El archivo $alias_file no existe. Instalando alias buscar en ~/.bashrc."
	echo 'alias buscar='$alias_file >> ~/.bashrc
	cp $this_file $alias_file
	chmod u+r+w+x $alias_file
	exit
fi


# COMANDO ELIMINAR: "x"
if [ $1 == "x" ]
then
	echo "Eliminando archivo $list_file."
        rm $list_file
	if [ -z $2 ]
	then
		echo "Nada para buscar."
		exit
	else
		# Desplazar parametro opcional para buscar
		shift
	fi
fi


#  BUSQUEDA
if [ -r $list_file ] && [ -s $list_file ]
then
        echo "El archivo $list_file existe. Buscando de nuevo."
	grep -e $1 $(cat $list_file) -l > $list_file
else
	echo "El archivo $list_file no existe. Buscando por primera vez."
	grep -e $1 -r ./ -l > $list_file
fi
cat $list_file
