#!/bin/bash

# CONFIGURATION
this_file="search" # name of this file
list_file="list.txt"
alias_file="$HOME/.$this_file"



# UNINSTALL COMMAND "u"
if [ ""$1 == "u" ] || [ ""$1 == "-u" ]
then
        echo "Uninstalling... :("
        rm $alias_file 2> /dev/null
	# remove alias in ~/.bashrc. Not implemented.
        exit
fi


# INSTALLATION OF ALIAS
if [ -r $alias_file ] && [ -s $alias_file ]
then
        # The file ~/.$alias_file exists.
	# If there are no parameters, exit.
	if [ -z $1 ]
	then
		exit
	fi
else
        echo "The "$alias_file" file does not exists. Installing "$this_file" alias in ~/.bashrc."
	echo 'alias '$this_file'='$alias_file >> ~/.bashrc
	cp $this_file $alias_file
	chmod u+r+w+x $alias_file
	exit
fi


# HELP COMMAND: "h"
if [ $1 == "h" ] || [ $1 == "-h" ]
then
	echo "Use: "$this_file" [term1 ... termN] Search one or multiple terms in the files in this folder, recursively, one at a time."
	echo "   How works:"
	echo "   Recursively search the files in this folder that contain all the terms. The results go to "$list_file"."
	echo "   In the next search, look over the files of the previous result. The results go to "$list_file" again."
	echo "   parameters:"
	echo "          u, -u Uninstall alias. (optional). "
	echo "          r, -r Remove previous result and Search recursively in this folder as the first time. (optional). "
	echo "          h, -h this help"
	exit
fi


# OPTIONAL REMOVE COMMAND: "r"
if [ $1 == "r" ] || [ $1 == "-r" ]
then
	echo "Removing the "$list_file" file."
        rm $list_file
	if [ $2 ]
	then
		# Shift optional parameter to search.
		shift
	else
		echo "Nothing to search."
		exit
	fi
fi


#  SINGLE SEARCH FUNCTION
function search()
{
	if [ -r $list_file ] && [ -s $list_file ]
	then
	        echo "Searching again. (The "$list_file" file exists)"
		grep -e $1 $(cat $list_file) -l > $list_file
	else
		echo "Searching for the first time. (The "$list_file" file does not exist or is empty)"
		grep -e $1 -r ./ -l > $list_file
	fi
	cat $list_file
}


# RECURSIVE SEARCH
while [ $1 ]
do
	echo "Searching "\"$1\"" ------------------------------"
	search $1
	shift
done
